version: 0.2
phases:
 install: # Install AWS cli, kubectl (needed for Helm) and Helm
  commands:
   — echo Set parameter
   — REGION=us-east-1
   — AWS_ACCOUNTID=[acc id]
   — ECR_NAME=[ECR name]
   — COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
   — IMAGE_TAG=${COMMIT_HASH:=latest}
   — EKS_NAME=[EKS name]
   — DEPLOYMENT_NAME=[deployment name]
   -REPOSITORY_URI=${AWS_ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_NAME}
   - echo Logging to AWS ECR…
   — aws ecr get-login-password — region $REGION | docker login — username AWS — password-stdin ${AWS_ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com
   - echo Installing necessary library…
   — apt-get update
   — apt install -y awscli git python3
   — curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
   — chmod +x ./aws-iam-authenticator
   — mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
   
 build: # Build Docker image and tag it with the commit sha
  commands:
   — echo Building docker image…
   — docker build -t $REPOSITORY_URI:latest — file Dockerfile .
   — docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build: # Push the Docker image to the ECR
  commands:
   — echo Pushing ECR…
   — docker push $REPOSITORY_URI:latest
   — docker push $REPOSITORY_URI:$IMAGE_TAG
