version: 0.2
phases:
 install: # Install AWS cli, kubectl (needed for Helm) and Helm
  commands:
   — echo Set parameter
   — REGION=us-east-1
   — AWS_ACCOUNTID=[acc id]
   — ECR_NAME=[ECR name]
   — COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
   — IMAGE_TAG=${COMMIT_HASH:=latest}
   — EKS_NAME=[EKS name]
   — DEPLOYMENT_NAME=[deployment name]
   - REPOSITORY_URI=${AWS_ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_NAME}
   - echo Logging to AWS ECR…
   - aws --version
   - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
   
 build: # Build Docker image and tag it with the commit sha
  commands:
   — echo Building docker image…
   — docker build -t $REPOSITORY_URI:latest — file Dockerfile .
   — docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build: # Push the Docker image to the ECR
  commands:
   — echo Pushing ECR…
   — docker push $REPOSITORY_URI:latest
   — docker push $REPOSITORY_URI:$IMAGE_TAG
