global:
  scrape_interval:     5s # Scrape new data every 5 seconds from your microservices
  evaluation_interval: 5s # Evaluate that data every 5 seconds.
scrape_configs:
  # identify microservices to monitor
  - job_name: 'curricula-tracker-service'
    # endpoint exposed by the service with data on health 
    metrics_path: '/actuator/prometheus'
    static_configs:
    # define host + port number
    # why accounts instead of localhost? The host name is Docker service name when calling another container
    - targets: ['curricular-tracker-service:5000']
